### ISSUE TITLE
discussion thread for new library

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/saya#1]
@StrangeWill and I were talking about having a library... Bensley and Vkirirom should use a shared Vue plugin handling all of our API calls/environment swaps.

Something we could maybe publish to NPM or something?

Saya should be this library, and perhaps building the bensley website is the best starting off point?

this would allow us to scale without having to manage a different front end app for every client.

**Comment by atharva3010** [comment]
Okay

**Comment by StrangeWill** [comment]
Yeah, in my mind it should cover these things:
- Swapping between staging/production API without the stuff we're currently doing (having divergent code in our repos), something we can easily flip a flag on compilation.
- _Ideally_ TypeScript, full type-safety checks for all API calls.
- All API endpoints available, nothing accessed "directly" by the Vue platforms.
- Automated tests would be nice.

**Comment by atharva3010** [comment]
Okay

**Comment by paulchrisluke** [comment]
@mort3za @atharva3010 this is our next priority. Our next sites are shinta mani wild, whynot.earth, and the cms. I intend to use this plugin through each project. How should we break up the tasks to build this?

**Comment by mort3za** [comment]
@paulchrisluke If I want to use that swagger-to-axios plugin, there is no need to break up the task. I work on this today and let you know to check the result.

**Comment by paulchrisluke** [comment]
@mort3za ok lets do it
https://giphy.com/gifs/VLoN2iW8ii3wA/html5

**Comment by mort3za** [comment]
@paulchrisluke @atharva3010 https://github.com/whynotearth/hotel-website-vkirirom.com/pull/164

**Comment by paulchrisluke** [comment]
lets start working on this: https://storybook.js.org/docs/guides/guide-vue/

Import all current known vue components so we can start fine tuning and prepping for next clients. We will probably use a lot of shinta mani wilds components in vkirirom as well.

**Comment by atharva3010** [comment]
You can take a look at this repository of mine if you need to quickly set it up.
https://github.com/atharva3010/geospoc
