### ISSUE TITLE
add gtm

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/saya#8]
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MSXLHVQ');</script>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MSXLHVQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by mort3za** [comment]
Wasn't `<iframe>` section inside `<noscript>` tag?

**Comment by paulchrisluke** [comment]
Sorry top one is for head bottom one is for body

**Comment by mort3za** [comment]
Yeah but I'm asking about `noscript` tag. This is the code for vkirirom:  
```
<!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PMXGLXR"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
```

**Comment by paulchrisluke** [comment]
you're right this was sloppy, was I drunk when I made this issue??? :P 

For the head:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MSXLHVQ');</script>
<!-- End Google Tag Manager -->
```

body:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MSXLHVQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

![image](https://user-images.githubusercontent.com/5694308/76605382-f7ed6a80-6542-11ea-8037-b328afec042a.png)

**Comment by mort3za** [comment]
lol maybe :D
